[[redirects]]
  from = "/api/*"
  to = "https://filmmarker-backend.up.railway.app/api/:splat"
  status = 302
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}
